#!/bin/bash
# Generates Config/Secrets.xcconfig from the repo-root .env file.
#
# Run this once after cloning (and again whenever .env changes):
#   ./Scripts/generate_secrets.sh
#
# Only CLIENT-SAFE keys are injected into the app bundle. Server-side keys
# (Gemini, Supabase secret/service-role) must never appear here — AGENTS.md §2.
#
# Supabase: inject the legacy JWT anon key (SUPABASE_ANON_KEY / eyJ…). supabase-swift
# 2.51.x still puts supabaseKey in Authorization: Bearer, which rejects non-JWT
# sb_publishable_… keys as Invalid JWT. Keep SUPABASE_PUBLISHABLE_KEY in .env for
# dashboard/docs; do not ship it to the iOS client until the SDK handles it.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT_FILE="$ROOT/pluri_fable_xcode/Config/Secrets.xcconfig"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "error: $ENV_FILE not found. Copy .env.example to .env and fill in values." >&2
    exit 1
fi

# Read KEY="value" from .env (ignores comments/blank lines).
env_value() {
    local key="$1"
    local line
    line=$(grep -E "^${key}=" "$ENV_FILE" | tail -n 1 || true)
    if [[ -z "$line" ]]; then
        echo "error: required key '$key' missing from .env" >&2
        exit 1
    fi
    local value="${line#*=}"
    value="${value%\"}"
    value="${value#\"}"
    if [[ -z "$value" ]]; then
        echo "error: required key '$key' is empty in .env" >&2
        exit 1
    fi
    echo "$value"
}

# xcconfig treats '//' as a comment even inside values; break it up with an
# empty build-setting substitution ($() resolves to nothing) so URLs survive.
escape_slashes() {
    printf '%s\n' "$1" | sed 's|//|/$()/|g'
}

CLIENT_KEYS=(
    SUPABASE_URL
    SUPABASE_ANON_KEY
    WORKOUTX_API_KEY
    WORKOUTX_ENDPOINT
    NUTRITION_API_KEY
    REVENUECAT_API_KEY
)

mkdir -p "$(dirname "$OUT_FILE")"
{
    echo "// Generated by Scripts/generate_secrets.sh — DO NOT EDIT, DO NOT COMMIT."
    echo "// Regenerate after changing .env."
    for key in "${CLIENT_KEYS[@]}"; do
        echo "PLURI_${key} = $(escape_slashes "$(env_value "$key")")"
    done
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
