#!/bin/bash
# Generates Config/Secrets.xcconfig from the repo-root .env file.
#
# Run this once after cloning (and again whenever .env changes):
#   ./Scripts/generate_secrets.sh
#
# Only CLIENT-SAFE keys are injected into the app bundle. Server-side keys
# (Gemini, Supabase secret/service-role) must never appear here — AGENTS.md §2.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT_FILE="$ROOT/pluri_fable_xcode/Config/Secrets.xcconfig"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "error: $ENV_FILE not found. Copy .env.example to .env and fill in values." >&2
    exit 1
fi

# Read KEY="value" from .env (ignores comments/blank lines).
env_value() {
    local key="$1"
    local line
    line=$(grep -E "^${key}=" "$ENV_FILE" | tail -n 1 || true)
    if [[ -z "$line" ]]; then
        echo "error: required key '$key' missing from .env" >&2
        exit 1
    fi
    local value="${line#*=}"
    value="${value%\"}"
    value="${value#\"}"
    if [[ -z "$value" ]]; then
        echo "error: required key '$key' is empty in .env" >&2
        exit 1
    fi
    echo "$value"
}

# Same, but an empty/absent value is allowed and means "feature disabled".
optional_env_value() {
    local key="$1"
    local line
    line=$(grep -E "^${key}=" "$ENV_FILE" | tail -n 1 || true)
    local value="${line#*=}"
    value="${value%\"}"
    value="${value#\"}"
    echo "$value"
}

# xcconfig treats '//' as a comment even inside values; break it up with an
# empty build-setting substitution ($() resolves to nothing) so URLs survive.
escape_slashes() {
    printf '%s\n' "$1" | sed 's|//|/$()/|g'
}

CLIENT_KEYS=(
    SUPABASE_URL
    SUPABASE_PUBLISHABLE_KEY
    WORKOUTX_API_KEY
    WORKOUTX_ENDPOINT
    NUTRITION_API_KEY
)

# Optional: an empty REVENUECAT_API_KEY means subscriptions are intentionally
# disabled for this build (no Purchases.configure, paywalls show unavailable).
OPTIONAL_CLIENT_KEYS=(
    REVENUECAT_API_KEY
)

mkdir -p "$(dirname "$OUT_FILE")"
{
    echo "// Generated by Scripts/generate_secrets.sh — DO NOT EDIT, DO NOT COMMIT."
    echo "// Regenerate after changing .env."
    for key in "${CLIENT_KEYS[@]}"; do
        echo "PLURI_${key} = $(escape_slashes "$(env_value "$key")")"
    done
    for key in "${OPTIONAL_CLIENT_KEYS[@]}"; do
        echo "PLURI_${key} = $(escape_slashes "$(optional_env_value "$key")")"
    done
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"

if [[ -z "$(optional_env_value REVENUECAT_API_KEY)" ]]; then
    echo "note: REVENUECAT_API_KEY is empty — subscriptions will be disabled in this build."
fi
